using Unity.Burst;
using Unity.Collections;
using Unity.Entities;
using Unity.Mathematics;
using Unity.Physics;
using Unity.Transforms;
using DIG.Aggro.Components;
using DIG.Surface;
using DIG.Vision.Components;
using DIG.Vision.Core;

namespace DIG.Aggro.Systems
{
    /// <summary>
    /// EPIC 15.19: Processes hearing events to generate threat from sounds.
    /// Sounds are 360-degree detection (no facing requirement) but still
    /// require line-of-sight (sound blocked by walls).
    /// 
    /// Hearing events are typically generated by:
    /// - Combat (attacks, abilities, explosions)
    /// - Movement (running, jumping - NOT walking/sneaking)
    /// - Allies dying or taking damage
    /// </summary>
    [WorldSystemFilter(WorldSystemFilterFlags.ServerSimulation | WorldSystemFilterFlags.LocalSimulation)]
    [UpdateInGroup(typeof(SimulationSystemGroup))]
    [UpdateAfter(typeof(DIG.Vision.Systems.DetectionSystem))]
    [BurstCompile]
    public partial struct HearingDetectionSystem : ISystem
    {
        private ComponentLookup<SurfaceNoiseModifier> _surfaceNoiseLookup;

        [BurstCompile]
        public void OnCreate(ref SystemState state)
        {
            state.RequireForUpdate<PhysicsWorldSingleton>();
            _surfaceNoiseLookup = state.GetComponentLookup<SurfaceNoiseModifier>(true);
        }

        [BurstCompile]
        public void OnUpdate(ref SystemState state)
        {
            var physicsWorld = SystemAPI.GetSingleton<PhysicsWorldSingleton>().PhysicsWorld;
            var occlusionFilter = VisionLayers.OcclusionFilter;
            _surfaceNoiseLookup.Update(ref state);
            
            // Collect all hearing events from emitters this frame
            var globalEvents = new NativeList<HearingEvent>(32, Allocator.Temp);
            
            foreach (var (eventBuffer, transform) in
                SystemAPI.Query<DynamicBuffer<HearingEvent>, RefRO<LocalTransform>>())
            {
                for (int i = 0; i < eventBuffer.Length; i++)
                {
                    globalEvents.Add(eventBuffer[i]);
                }
            }
            
            // Skip if no events
            if (globalEvents.Length == 0)
            {
                globalEvents.Dispose();
                return;
            }
            
            // Process each listener (AI with hearing)
            foreach (var (sensor, config, aggroState, transform, entity) in
                SystemAPI.Query<RefRO<DetectionSensor>, RefRO<AggroConfig>, RefRW<AggroState>,
                    RefRO<LocalTransform>>()
                .WithAll<ThreatEntry>()
                .WithEntityAccess())
            {
                float hearingRadius = sensor.ValueRO.HearingRadius;
                
                // Skip if no hearing
                if (hearingRadius <= 0f)
                    continue;
                
                // Get mutable buffer outside query
                var threatBuffer = SystemAPI.GetBuffer<ThreatEntry>(entity);
                
                float3 listenerPos = transform.ValueRO.Position + 
                    new float3(0f, sensor.ValueRO.EyeHeight, 0f);
                float hearingThreat = config.ValueRO.HearingThreatValue;
                int maxTargets = config.ValueRO.MaxTrackedTargets;
                
                // Check each sound event
                for (int e = 0; e < globalEvents.Length; e++)
                {
                    var soundEvent = globalEvents[e];
                    
                    // Skip sounds from self
                    if (soundEvent.SourceEntity == entity)
                        continue;
                    
                    // EPIC 16.10: Apply surface noise modifier from source entity
                    float surfaceNoise = _surfaceNoiseLookup.HasComponent(soundEvent.SourceEntity)
                        ? _surfaceNoiseLookup[soundEvent.SourceEntity].Multiplier
                        : 1.0f;
                    float adjustedLoudness = soundEvent.Loudness * surfaceNoise;

                    // Calculate effective range (base hearing * loudness)
                    float effectiveRange = math.min(hearingRadius, soundEvent.MaxRange) * adjustedLoudness;
                    float distance = math.distance(listenerPos, soundEvent.Position);

                    if (distance > effectiveRange)
                        continue;

                    // Check line-of-sight for sound (blocked by walls)
                    bool canHear = DetectionQueryUtility.HasLineOfSight(
                        in physicsWorld, listenerPos, soundEvent.Position, occlusionFilter);

                    if (!canHear)
                        continue;

                    // Calculate threat based on distance (louder = more threat, closer = more threat)
                    float distanceFactor = 1f - (distance / effectiveRange);
                    float threatValue = hearingThreat * adjustedLoudness * distanceFactor;
                    
                    if (threatValue < 0.1f)
                        continue;
                    
                    // Find or create threat entry
                    Entity sourceEntity = soundEvent.SourceEntity;
                    int existingIndex = -1;
                    
                    for (int t = 0; t < threatBuffer.Length; t++)
                    {
                        if (threatBuffer[t].SourceEntity == sourceEntity)
                        {
                            existingIndex = t;
                            break;
                        }
                    }
                    
                    if (existingIndex >= 0)
                    {
                        // Add threat to existing entry
                        var entry = threatBuffer[existingIndex];
                        entry.ThreatValue += threatValue;
                        entry.LastKnownPosition = soundEvent.Position;
                        entry.SourceFlags |= ThreatSourceFlags.Hearing;
                        // Don't mark as visible - hearing doesn't reveal position precisely
                        threatBuffer[existingIndex] = entry;
                    }
                    else if (threatBuffer.Length < maxTargets)
                    {
                        // New threat entry from hearing
                        threatBuffer.Add(new ThreatEntry
                        {
                            SourceEntity = sourceEntity,
                            ThreatValue = threatValue,
                            LastKnownPosition = soundEvent.Position,
                            TimeSinceVisible = 999f, // Not visible, just heard
                            IsCurrentlyVisible = false,
                            SourceFlags = ThreatSourceFlags.Hearing
                        });
                    }
                }
            }
            
            // Clear all hearing event buffers for next frame
            foreach (var eventBuffer in SystemAPI.Query<DynamicBuffer<HearingEvent>>())
            {
                eventBuffer.Clear();
            }
            
            globalEvents.Dispose();
        }
    }
}
