#if UNITY_EDITOR
using System.Collections.Generic;
using UnityEngine;

namespace DIG.Roguelite.Editor
{
    public enum CoverageSeverity { Info, Warning, Error }

    public struct CoverageIssue
    {
        public CoverageSeverity Severity;
        public string Category;       // "Zones", "Encounters", "Rewards", "Meta", "Economy"
        public string Message;
        public ScriptableObject Asset; // Clickable — ping in Project window
    }

    /// <summary>
    /// EPIC 23.7: Reusable coverage report. Generated by ContentCoverageAnalyzer.
    /// Displayed by ContentCoverageModule. Also used by RogueliteSetupWizard validation.
    /// </summary>
    public class ContentCoverageReport
    {
        public List<CoverageIssue> Issues = new();
        public int ErrorCount;
        public int WarningCount;
        public int InfoCount;
        public float CompletenessScore;   // 0-100%. Errors = -20 each, Warnings = -5 each
        public double GeneratedTimestamp;
    }
}
#endif
